import Header from "../components/common/Header";
import { Dancing_Script } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dancing-script",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dancingScript.variable}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
